import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div class="w-full h-screen" className={styles.container}>
      <Head>
        <title>merzdigital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'></link>
      </Head>

      <main className="flex justify-center h-full">
          <img src="spoon.png" className="h-2/3 object-cover"></img>
      </main>

      <footer className="sticky bottom-0 bg-white p-5 h-30">
      <div className="flex justify-center items-center flex-col">

       <div className="font-bold text-md pb-5" style={{ color: '#9B575D' }}>TELL US ABOUT YOUR CREATIVE NEEDS</div>
         <div className="flex flex-row space-x-3 ">
         <a href="">
           <img src="facebook icon.svg" className="w-10" />
         </a>
         <a href="">
         <img src="instagram icon.svg" className="w-10" />
         </a>
         <a href="">
         <img src="twitter icon.svg" className="w-10" />
         </a>
         </div>
       </div>
      </footer>
    </div>
  )
}
